baseURL = "magento-cli/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "magento-cli docs"
theme = "hugo-theme-learn"
themesDir = ".hugo/themes/"

contentDir = "docs"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/superterran/magento-cli/tree/main/docs"
  description = "Documentation for Magento-cli"
  author = "Doug Hatcher"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "magento-cli"
weight = 1
languageName = "English"
landingPageURL = "/en"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/superterran/magento-cli"
weight = 10


