#!/usr/bin/env variant
tasks:
  configure:
    description: configures backend to use this codebase
    script: |
      php bin/magento setup:store-config:set --base-url='http://{{ get "host" }}:{{ get "port" }}/      
