#!/usr/bin/env variant
tasks:
  down:
    description: downs the docker compositions
    parameters:
    - name: project
      type: string
      description: project slug
      default: localhost
    script: |
      docker-compose --project-name {{ get "project" }} -f $MAGECLI__PATH/services/database.yaml -f $MAGECLI__PATH/services/elasticsearch.yaml down
