#!/usr/bin/env variant
tasks:
  down:
    description: downs the docker compositions
    script: |
      docker-compose --project-name {{ get "project" }} -f $MAGECLI_PATH/services/database.yaml -f $MAGECLI_PATH/services/elasticsearch.yaml down
