#!/usr/bin/env variant

tasks:
  install: 
    description: installs magento to the backend services
    parameters: *global
    script: 
    - *envvars
    - |
      php -d memory_limit=-1 bin/magento setup:install \
        --base-url=http://{{ get "host" }}:{{ get "port" }} \
        --db-host={{ get "db-host" }}  \
        --db-name={{ get "db-name" }} \
        --db-user={{ get "db-user" }} \
        --db-password={{ get "db-pass" }} \
        --admin-firstname={{ get "install-firstname" }} \
        --admin-lastname={{ get "install-lastname" }} \
        --admin-email={{ get "install-email" }} \
        --admin-user={{ get "install-username" }} \
        --admin-password={{ get "install-password" }} \
        --language={{ get "install-language" }} \
        --currency={{ get "install-currency" }} \
        --timezone={{ get "install-timezone" }} \
        --use-rewrites={{ get "install-use-rewrites" }} \
        --search-engine={{ get "install-search-engine" }} \
        --elasticsearch-host={{ get "es-host" }} \
        --elasticsearch-port={{ get "es-port" }}
