#!/usr/bin/env variant
tasks:
  install:
    parameters: &global-parameters
    - name: firstname
      type: string
      description: first name of default admin user
      default: Magento
    - name: lastname
      type: string
      description: last name of default admin user
      default: User
    - name: email
      type: string
      description: email of default admin user
      default: user@example.com
    - name: username
      type: string
      description: username of default admin user
      default: admin
    - name: password
      type: string
      description: password of default admin user
      default: admin123
    - name: language
      type: string
      description: default langauge
      default: en_US
    - name: currency
      type: string
      description: default currency
      default: USD
    - name: currency
      type: string
      description: default currency
      default: USD
    - name: timezone
      type: string
      description: default timezone
      default: America/Chicago
    - name: use-rewrites
      type: string
      description: use url rewrites
      default: 1
    - name: search-engine
      type: string
      description: configured search engine for magento backend
      default: elasticsearch7
    description: installs magento to the backend services
    script: |
      php -d memory_limit=-1 bin/magento setup:install \
        --base-url=http://$MAGECLI_BASE_URL \
        --db-host=$MAGECLI_DB_HOST \
        --db-name=$MAGECLI_DB_NAME \
        --db-user=$MAGECLI_DB_USER \
        --db-password=$MAGECLI_DB_PASS \
        --admin-firstname=$MAGECLI_ADMIN_FIRSTNAME \
        --admin-lastname=$MAGECLI_ADMIN_LASTNAME \
        --admin-email=$MAGECLI_ADMIN_EMAIL \
        --admin-user=$MAGECLI_ADMIN_USER \
        --admin-password=$MAGECLI_ADMIN_PASSWORD \
        --language=$MAGECLI_LANGUAGE \
        --currency=$MAGECLI_CURRENCY \
        --timezone=$MAGECLI_TIMEZONE \
        --use-rewrites=$MAGECLI_USE_REWRITES \
        --search-engine=$MAGECLI_SEARCH_ENGINE \
        --elasticsearch-host=$MAGECLI_ELASTICSEARCH_HOST \
        --elasticsearch-port=$MAGECLI_ELASTICSEARCH_PORT
