#!/usr/bin/env variant
tasks:
  logs:
    description: shows logs of backend services
    script: 
      - *envvars
      
      - docker-compose --project-name {{ get "project" }} -f .magento-cli/tmp/services/database.yaml -f .magento-cli/tmp/services/elasticsearch.yaml logs
