#!/usr/bin/env variant
definitions:
  parameters: &global-parameters
    - name: host
      type: string
      description: hostname to serve
      default: 0.0.0.0
    - name: port
      type: string
      description: php server port
      default: "8080"
    - name: routes
      type: string
      description: routes used for local development server
      default: $(pwd)/pub/ $(pwd)/phpserver/router.php