#!/usr/bin/env variant
tasks:
  serve:
    parameters: *global 
    script: |
      COMMAND="{{ get "php-bin-cmd" }} {{ get "host" }}:{{ get "port" }} -t {{ get "routes" }}"
      echo $COMMAND
      $COMMAND