#!/usr/bin/env variant
tasks:
  serve:
    parameters:
    - name: baseurl
      type: string
      description: "base url"
      default: "localhost:8200"
    script: |
      php -S {{ get "baseurl" }} -t $(pwd)/pub/ $(pwd)/phpserver/router.php