#!/usr/bin/env variant
tasks:
  up:
    description: ups the docker compositions
    script: |
      docker-compose --project-name {{ get "project" }} -f $MAGECLI_PATH/services/database.yaml -f $MAGECLI_PATH/services/elasticsearch.yaml up -d && sleep 3
